// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIrl69sc4xSF4ZKjW0C0Uc_sexNzPLsqI',
    appId: '1:210077339842:android:2119a136b30be2b3d6eb5b',
    messagingSenderId: '210077339842',
    projectId: 'voygo-b94ae',
    databaseURL: 'https://voygo-b94ae-default-rtdb.firebaseio.com',
    storageBucket: 'voygo-b94ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVPgtHfo_BamkkpRriLdJBDoAZv3ktcOc',
    appId: '1:210077339842:ios:15232ddb5033bef1d6eb5b',
    messagingSenderId: '210077339842',
    projectId: 'voygo-b94ae',
    databaseURL: 'https://voygo-b94ae-default-rtdb.firebaseio.com',
    storageBucket: 'voygo-b94ae.firebasestorage.app',
    iosBundleId: 'com.example.voygo',
  );
}
